USE [REWORKBASE]
GO

SELECT * INTO REWORKTEMP FROM REWORK;
GO

ALTER TABLE [dbo].[REWORKDETAIL] DROP CONSTRAINT [FK_REWORKDETAIL_REWORK]
GO

DROP TABLE dbo.[REWORK];
GO

CREATE TABLE [dbo].[REWORK](
	[REWORKNUMBER] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [nvarchar](max) NOT NULL,
	[PROJECT] [nvarchar](150) NOT NULL,
	[FIELD1] [nvarchar](150) NULL,
	[FIELD2] [nvarchar](150) NULL,
	[ISDELETED] [bit] NOT NULL,
	[ADDDATE] [datetime] NOT NULL,
	[ADDWHO] [nvarchar](20) NULL,
	[EDITWHO] [nvarchar](20) NULL,
	[EDITDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_REWORK] PRIMARY KEY CLUSTERED 
(
	[REWORKNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[REWORK] ADD  DEFAULT ((0)) FOR [ISDELETED]
GO

ALTER TABLE [dbo].[REWORK] ADD  CONSTRAINT [DF__REWORK__ADDDA__]  DEFAULT (getdate()) FOR [ADDDATE]
GO

ALTER TABLE [dbo].[REWORK] ADD  CONSTRAINT [DF__REWORK__ADDWH__]  DEFAULT (user_name()) FOR [ADDWHO]
GO

ALTER TABLE [dbo].[REWORK] ADD  CONSTRAINT [DF__REWORK__EDITW__]  DEFAULT (user_name()) FOR [EDITWHO]
GO

ALTER TABLE [dbo].[REWORK] ADD  CONSTRAINT [DF__REWORK__EDITD__]  DEFAULT (getdate()) FOR [EDITDATE]
GO

SET IDENTITY_INSERT dbo.[REWORK] ON;  
GO 

INSERT INTO dbo.[REWORK] 
		([REWORKNUMBER],[DESCRIPTION],[PROJECT],[FIELD1],[FIELD2],[ISDELETED],[ADDDATE],[ADDWHO],[EDITWHO],[EDITDATE])
SELECT [REWORKNUMBER],[DESCRIPTION],'Монетка',[TASK],[TASKMONETKA],[ISDELETED],[ADDDATE],[ADDWHO],[EDITWHO],[EDITDATE]
FROM dbo.REWORKTEMP
GO

SET IDENTITY_INSERT dbo.[REWORK] OFF;  
GO

ALTER TABLE [dbo].[REWORKDETAIL]  WITH CHECK ADD  CONSTRAINT [FK_REWORKDETAIL_REWORK] FOREIGN KEY([REWORKNUMBER])
REFERENCES [dbo].[REWORK] ([REWORKNUMBER])
GO

ALTER TABLE [dbo].[REWORKDETAIL] CHECK CONSTRAINT [FK_REWORKDETAIL_REWORK]
GO

DROP TABLE REWORKTEMP;



