USE [REWORKBASE]
GO

/****** Create tables  ******/
--DROP TABLE [dbo].[REWORK] 
CREATE TABLE [dbo].[REWORK](
	[REWORKNUMBER] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [nvarchar](max) NOT NULL,
	[TASK] [nvarchar](150) NULL,
	[TASKMONETKA] [nvarchar](150) NULL,
	ISDELETED bit DEFAULT 0 NOT NULL,
	[ADDDATE] [datetime] NOT NULL,
	[ADDWHO] [nvarchar](20) NULL,
	[EDITWHO] [nvarchar](20) NULL,
	[EDITDATE] [datetime] NOT NULL,
	CONSTRAINT [PK_REWORK] PRIMARY KEY CLUSTERED ([REWORKNUMBER])
)

ALTER TABLE [dbo].[REWORK] ADD  CONSTRAINT [DF__REWORK__ADDDA__]  DEFAULT (getutcdate()) FOR [ADDDATE]
GO

ALTER TABLE [dbo].[REWORK] ADD  CONSTRAINT [DF__REWORK__ADDWH__]  DEFAULT (user_name()) FOR [ADDWHO]
GO

ALTER TABLE [dbo].[REWORK] ADD  CONSTRAINT [DF__REWORK__EDITW__]  DEFAULT (user_name()) FOR [EDITWHO]
GO

ALTER TABLE [dbo].[REWORK] ADD  CONSTRAINT [DF__REWORK__EDITD__]  DEFAULT (getutcdate()) FOR [EDITDATE]
GO

--DROP TABLE [dbo].[REWORKDETAIL] 
CREATE TABLE [dbo].[REWORKDETAIL](
	[SERIALKEY] [int] IDENTITY(1,1) NOT NULL,
	[REWORKNUMBER] [int] NOT NULL,
	[SERVER] [nvarchar](30) NOT NULL,
	[STATUS] [nvarchar](30) NULL,
	[ADDDATE] [datetime] NULL,
	[ADDWHO] [nvarchar](20) NULL,
	[EDITWHO] [nvarchar](20) NULL,
	[EDITDATE] [datetime] NULL,
 CONSTRAINT [PK_REWORKDETAIL] PRIMARY KEY CLUSTERED ([SERIALKEY])
 )

ALTER TABLE [dbo].[REWORKDETAIL] ADD  CONSTRAINT [DF__REWORKDETAIL__ADDDA__]  DEFAULT (getutcdate()) FOR [ADDDATE]
GO

ALTER TABLE [dbo].[REWORKDETAIL] ADD  CONSTRAINT [DF__REWORKDETAIL__ADDWH__]  DEFAULT (user_name()) FOR [ADDWHO]
GO

ALTER TABLE [dbo].[REWORKDETAIL] ADD  CONSTRAINT [DF__REWORKDETAIL__EDITW__]  DEFAULT (user_name()) FOR [EDITWHO]
GO

ALTER TABLE [dbo].[REWORKDETAIL] ADD  CONSTRAINT [DF__REWORKDETAIL__EDITD__]  DEFAULT (getutcdate()) FOR [EDITDATE]
GO

ALTER TABLE [dbo].[REWORKDETAIL]  WITH CHECK ADD  CONSTRAINT [FK_REWORKDETAIL_REWORK] FOREIGN KEY([REWORKNUMBER])
REFERENCES [dbo].[REWORK] ([REWORKNUMBER])
GO

ALTER TABLE [dbo].[REWORKDETAIL] CHECK CONSTRAINT [FK_REWORKDETAIL_REWORK]
GO
